version: 2.1
orbs:
  node: circleci/node@5.1.0
  codecov/codecov@3.2.4
jobs:
  job-test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn migrate:up --env test
          name: Init db
      - run:
          command: yarn test
          name: Run tests

workflows:
  build-and-test:
    jobs:
      - job-test
